---
- name: Install rcm
  dnf:
    name:
      - rcm

- name: Clone Dotfiles   # noqa 401
  git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ dotfiles.name }}/{{ dotfiles.destination }}
    accept_hostkey: true
    update: false
  become: true
  become_user: "{{ dotfiles.name }}"

- name: Install Dotfiles
  command: rcup -d /home/{{ dotfiles.name }}/{{ dotfiles.destination }}
  when: dotfiles is defined
  become: true
  become_user: "{{ dotfiles.name }}"

- name: Set user groups
  user:
    name: "{{ dotfiles.name }}"
    groups:
      - wheel
      - video
      - pkg-build
