---
- name: Install rcm
  dnf:
    name:
      - rcm

- name: Clone Dotfiles
  git: repo={{ dotfiles.url }} dest=/home/{{ dotfiles.name }}/{{ dotfiles.destination }} accept_hostkey=yes update=no
  become: yes
  become_user: "{{ dotfiles.name }}"

- name: Install Dotfiles
  command: rcup -d /home/{{ dotfiles.name }}/{{ dotfiles.destination }}
  when: dotfiles is defined
  become: yes
  become_user: "{{ dotfiles.name }}"

- name: Set user groups
  user:
    name: {{ dotfiles.name }}
    groups:
      - wheel
      - video
      - pkg-build