---
- hosts: localhost
  become: true
  vars_files:
    - variables/versions.yml
    - variables/rice.yml
  roles:
    - {role: x230_drivers, tags: ["x230_drivers"]}
    - {role: laptop_optimization, tags: ["laptop_optimization"]}
    - {role: cli_tools, tags: ["cli_tools"]}
    - {role: desktop, tags: ["desktop"]}
    - {role: desktop_apps, tags: ["desktop_apps"]}
    - {role: rice, tags: ["rice"]}
    - {role: school, tags: ["school"]}
    - {role: container_and_virt, tags: ["container_and_virt"]}
    - {role: android_tools, tags: ["android_tools"]}
