---
- name: Enable Fedora Copr for bpremo/i3desktop
  command: dnf copr enable -y bpremo/i3desktop creates=/etc/yum.repos.d/_copr_gregw-i3desktop.repo warn=false

- name: Install Windows Manager
  dnf:
    name:
      - i3-gaps

- name: Install Polybar
  dnf:
    name:
      - polybar

