- name: Install CLI Tools
  dnf:
    name:
      - bash-completion
      - git
      - neovim
      - whois
      - traceroute
      - unzip
      - htop
      - usbutils
      - tlp

- name: Install Terminal
  dnf:
    name:
      - rxvt-unicode

- name: Install Fedora Workstation Repositories
  dnf:
    name: 
      - fedora-workstation-repositories

- name: Enable Google Chrome
  command: dnf config-manager --set-enabled google-chrome

- name: Install Google Chrome
  dnf:
    name:
      - google-chrome-stable

- name: Import Visual Studio Key
  command: sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc

- name: Add Visual Studio Repository
  command: sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

- name: Install Visual Studio Code
  dnf: 
    name:
      - code

- name: Install Google Noto Fonts
  dnf:
    name:
      - google-noto-sans-fonts
      - google-noto-emoji-fonts
      - google-noto-sans-mono-fonts

- name: Install the rpmfusion repo packages
  dnf:
    name:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm

