---
name: Check Syntax
on:  # noqa 401
  - push

jobs:
  syntax:
    name: Check Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: install dependencies
        run: |
          pip3 install homeassistant
          pip3 install ansible
          pip3 install ansible-lint
      - name: test syntax
        run: |
          ansible-playbook playbook.yml --syntax-check
      - name: linting
        run: |
          ansible-lint playbook.yml
